[project]
name = "expense-tracker"
version = "1.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.10"
dependencies = [
    "flask~=3.1.2",
]

[dependency-groups]
dev = [
    "flask-cors~=6.0.2",
]
